// Freehold iOS FFI - C Header for Swift Integration
// Generated by cbindgen - do not edit manually
//
// This header provides C-compatible bindings for the Freehold client
// library, allowing integration with Swift via C interop.

#ifndef FREEHOLD_FFI_H
#define FREEHOLD_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ============================================================================
// Types
// ============================================================================

/**
 * FFI-safe relay state enum
 */
typedef enum FreeholdRelayState {
    FREEHOLD_RELAY_STATE_DISCONNECTED = 0,
    FREEHOLD_RELAY_STATE_PENDING = 1,
    FREEHOLD_RELAY_STATE_CONNECTED = 2,
} FreeholdRelayState;

/**
 * FFI-safe status update type enum
 */
typedef enum FreeholdStatusType {
    FREEHOLD_STATUS_TYPE_RELAY_STATE = 0,
    FREEHOLD_STATUS_TYPE_NEIGHBOR_DISCOVERED = 1,
    FREEHOLD_STATUS_TYPE_ERROR = 2,
    FREEHOLD_STATUS_TYPE_NONE = 3,
} FreeholdStatusType;

/**
 * FFI-safe status update structure
 */
typedef struct FreeholdStatusUpdate {
    FreeholdStatusType update_type;
    char *relay_addr;      // null-terminated string or NULL
    FreeholdRelayState relay_state;
    char *neighbor_ip;     // null-terminated string or NULL
    char *error_message;   // null-terminated string or NULL
} FreeholdStatusUpdate;

/**
 * FFI-safe configuration structure
 */
typedef struct FreeholdConfig {
    const char *relay_host;
    uint16_t relay_port;
    uint16_t claim_port;
    uint16_t h3_bind_port;
    const char *backend_host;
    uint16_t backend_port;
    const char *domain;
    bool auto_discover;
} FreeholdConfig;

/**
 * Callback type for packet handling in VPN mode
 */
typedef void (*PacketCallback)(const uint8_t *data, size_t len, void *context);

// ============================================================================
// Core Functions
// ============================================================================

/**
 * Initialize the Freehold FFI layer. Call this once at app startup.
 *
 * @return 0 on success, -1 on failure.
 */
int32_t freehold_init(void);

/**
 * Create and start the Freehold service.
 *
 * @param config Pointer to configuration structure. All string fields must be
 *               valid null-terminated UTF-8 strings.
 * @return 0 on success, -1 on failure.
 */
int32_t freehold_start(const FreeholdConfig *config);

/**
 * Stop the Freehold service.
 *
 * @return 0 on success, -1 on failure.
 */
int32_t freehold_stop(void);

/**
 * Check if the service is running.
 *
 * @return 1 if running, 0 if not running.
 */
int32_t freehold_is_running(void);

/**
 * Poll for the next status update (non-blocking).
 *
 * @return Pointer to FreeholdStatusUpdate if available, NULL if no update.
 *         The caller must free the returned pointer with freehold_free_status_update.
 */
FreeholdStatusUpdate *freehold_poll_status(void);

/**
 * Free a status update returned by freehold_poll_status.
 *
 * @param update Pointer returned by freehold_poll_status. May be NULL.
 */
void freehold_free_status_update(FreeholdStatusUpdate *update);

/**
 * Free a string allocated by the FFI layer.
 *
 * @param s Pointer to string. May be NULL.
 */
void freehold_free_string(char *s);

/**
 * Get the library version.
 *
 * @return Pointer to a null-terminated version string. Do not free this pointer.
 */
const char *freehold_version(void);

// ============================================================================
// VPN / Network Extension Functions
// ============================================================================

/**
 * Initialize VPN mode for use with NEPacketTunnelProvider.
 *
 * The callback will be invoked when packets need to be written to the tunnel.
 *
 * @param callback Function to call when packets should be written to tunnel.
 * @param context User context pointer passed to callback.
 * @return 0 on success, -1 on failure.
 */
int32_t freehold_vpn_init(PacketCallback callback, void *context);

/**
 * Process an incoming packet from the tunnel (device -> network).
 *
 * @param data Pointer to packet data.
 * @param len Length of packet data in bytes.
 * @return 0 on success, -1 on failure.
 */
int32_t freehold_vpn_process_packet(const uint8_t *data, size_t len);

/**
 * Stop VPN mode.
 *
 * @return 0 on success, -1 on failure.
 */
int32_t freehold_vpn_stop(void);

#endif /* FREEHOLD_FFI_H */
